server:
  host: "${HOST:localhost}"
  port: ${PORT:5334}
  mode: "${GIN_MODE:debug}"
  cert_file: "${CERT_FILE:}"
  key_file: "${KEY_FILE:}"

database:
  type: "${DB_TYPE:postgres}"
  host: "${DB_HOST:localhost}"
  port: ${DB_PORT:5432}
  username: "${DB_USERNAME:postgres}"
  password: "${DB_PASSWORD:postgres}"
  database: "${DB_DATABASE:ripple}"
  ssl_mode: "${DB_SSL_MODE:disable}"
  timezone: "${DB_TIMEZONE:UTC}"

logger:
  level: "${LOG_LEVEL:info}"
  format: "${LOG_FORMAT:console}"
  filename: "${LOG_FILENAME:logs/ripple.log}"
  max_size: ${LOG_MAX_SIZE:10}
  max_age: ${LOG_MAX_AGE:30}
  max_backups: ${LOG_MAX_BACKUPS:5}
  local_time: ${LOG_LOCAL_TIME:true}
  compress: ${LOG_COMPRESS:true}
  console: ${LOG_CONSOLE:true}
  time_format: "${LOG_TIME_FORMAT:2006-01-02 15:04:05}"
  timezone: "${LOG_TIMEZONE:Local}"

notion:
  token: "${NOTION_TOKEN:}"
  database_id: "${NOTION_DATABASE_ID:}"
  api_version: "${NOTION_API_VERSION:2022-06-28}"

scheduler:
  sync_interval: "${SYNC_INTERVAL:30m}"
  enabled: ${SCHEDULER_ENABLED:true}

publisher:
  al_folio:
    enabled: ${AL_FOLIO_ENABLED:false}
    repo_url: "${AL_FOLIO_REPO_URL:https://github.com/iFurySt/ifuryst.github.io}"
    branch: "${AL_FOLIO_BRANCH:master}"
    workspace_dir: "${AL_FOLIO_WORKSPACE:workspace}"
    base_url: "${AL_FOLIO_BASE_URL:https://ifuryst.github.io}"
    commit_message: "${AL_FOLIO_COMMIT_MESSAGE:Add new post via Ripple}"
    auto_publish: ${AL_FOLIO_AUTO_PUBLISH:false}
  wechat_official:
    enabled: ${WECHAT_OFFICIAL_ENABLED:false}
    app_id: "${WECHAT_OFFICIAL_APP_ID:}"
    app_secret: "${WECHAT_OFFICIAL_APP_SECRET:}"
    auto_publish: ${WECHAT_OFFICIAL_AUTO_PUBLISH:false}
    need_open_comment: ${WECHAT_OFFICIAL_NEED_OPEN_COMMENT:0}
    only_fans_can_comment: ${WECHAT_OFFICIAL_ONLY_FANS_CAN_COMMENT:0}
    default_thumb_media_id: "${WECHAT_OFFICIAL_DEFAULT_THUMB_MEDIA_ID:}"
